# Generated by Django 3.2.5 on 2021-07-01 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outing',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='cox',
        ),
        migrations.AddField(
            model_name='inouting',
            name='type',
            field=models.CharField(choices=[('RW', 'rower'), ('CX', 'cox'), ('CC', 'coach')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
