# Generated by Django 3.2.5 on 2021-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_inteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='type',
            field=models.CharField(choices=[('RW', 'rower'), ('CX', 'cox'), ('CC', 'coach')], default='RW', max_length=2),
            preserve_default=False,
        ),
    ]
