# Generated by Django 3.2.5 on 2021-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_available_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CF', 'confirmed'), ('CC', 'cancelled')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
