# Generated by Django 3.2.5 on 2021-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_outing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowerprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='rowerprofile',
            name='crsid',
            field=models.CharField(default='abc123', max_length=8),
            preserve_default=False,
        ),
    ]
