# Generated by Django 3.2.5 on 2021-12-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_hasbeenmailedouting'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='comment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
