# Generated by Django 3.2.5 on 2021-12-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_available_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
