# Generated by Django 3.2.5 on 2022-01-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220130_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.team'),
        ),
    ]
