# Generated by Django 3.2.5 on 2021-07-05 11:00

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0006_auto_20210705_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='rowerprofile',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
