# Generated by Django 3.2.5 on 2021-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20210705_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErgWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('subSeconds', models.IntegerField()),
            ],
        ),
    ]
