# Generated by Django 3.2.5 on 2022-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_announcement_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergworkout',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
