# Generated by Django 3.2.5 on 2021-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210712_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='type',
            field=models.CharField(choices=[('RW', 'rower'), ('CX', 'cox'), ('CC', 'coach')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inouting',
            name='type',
            field=models.CharField(choices=[('RW', 'rower'), ('CX', 'cox'), ('CC', 'coach')], max_length=2),
        ),
        migrations.AlterField(
            model_name='outing',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CF', 'confirmed'), ('CC', 'cancelled')], max_length=2),
        ),
    ]
